<!-- Generated by Microi吾码 VSCode Extension - DO NOT REMOVE THIS LINE -->
# Microi吾码 V8引擎 API 知识库

> 此文件由 Microi吾码 VS Code 插件自动生成，为 AI 编程助手提供 V8 引擎 API 上下文。

## 概述

Microi吾码是一个开源 AI 低代码平台（.NET10 + Vue3 + Redis），V8引擎（基于 Jint，.NET 上的 JavaScript 解释器）是其核心脚本引擎。
用户在"接口引擎"和"表单引擎V8事件"中编写 JavaScript 代码，通过全局对象 `V8` 访问后端能力。

## 接口引擎

接口引擎允许用户用 JavaScript 编写后端 API 逻辑。每个接口引擎有唯一的 `ApiEngineKey`。
在线编写，保存即生效，支持 Get/Post 请求，支持 form/json/url 三种参数格式。

**返回值方式：**
```js
return { Code: 1, Data: [1,2,3] };       // 带Code对象仅Code=1提交，其他值回滚
return '字符串';                           // 直接返回字符串
return '<html>...</html>';                 // 返回HTML
// 返回文件（需开启"响应文件"）
return { Code:1, Data:{ FileName:'a.png', ContentType:'image/png', FileByteBase64: base64 } };
```

**配置项：** StopHttp（禁止外部调用）、ApiAddress（自定义地址）、分布式锁、允许匿名调用、响应文件

**异步与后台任务：** 请求内异步方法使用 `await`；`setTimeout` / `Task.Run` 不能保证请求返回后继续工作，因为 Engine、租户上下文和事务会被释放。预计超过 2 分钟、500 条、1000 个扇出子操作、100 次外部调用或安装/初始化/迁移/备份类工作，使用 `V8.ApiEngine.RunBackground` 并配置稳定 `IdempotencyKey`。业务记录至少写“处理中”状态和 `BackgroundTaskId`；通过 `V8.Method.UpdateBackgroundTask({Current,Total,Msg})` 上报真实单位，平台根据实际吞吐估算结束时间。总量未知时不要伪造百分比；超过 10 分钟的工作必须按 checkpoint 分片、每片独立事务。

**Jint预算与嵌套：** `LimitMemory` 是单层Jint执行期间的累计托管分配，不是实时堆或预留内存。`V8.ApiEngine.Run` 多层调用是正常能力；接口嵌套与JavaScript函数递归是两种限制。用 `V8.Limits` 查看本片有效预算。接口引擎与表单后端 V8 事件都使用正向 `v8Limit`：缺失、`null` 或 `false` 不设置 Jint 单次超时、语句、递归和累计分配预算；设为 `true` 才应用配置值。旧 `v8Unlimited` 只在新字段不存在时反向兼容。进程常驻内存保护、请求取消、并发、嵌套深度、权限和数据库安全边界在两种模式下始终生效。

---

## V8.FormEngine — 表单引擎 CRUD

所有方法第一个参数为表名或表Key（不区分大小写），第二个参数为查询/操作条件对象。后端可信 V8 调用不要求 `_SysMenuId`；浏览器 HTTP 必须通过真实菜单、历史授权推断、直接表权限或受控 TableChild 委托。外部 JSON 不能伪造可信调用，`_InvokeType` 也不是授权标记。

```js
// 获取单条数据（Code=2表示数据不存在）
var result = V8.FormEngine.GetFormData('Sys_User', {
  _Where: [['Account', '=', 'admin']],
  _SelectFields: ['Id', 'Account', 'Name']
});

// 获取列表（分页）
var result = V8.FormEngine.GetTableData('Sys_User', {
  Ids: [1,2,3],                              // 按Id列表查
  _Where: [['Status', '=', 1]],
  _SelectFields: ['Id', 'Account', 'Name'],
  _OrderBy: 'CreateTime',
  _OrderByType: 'DESC',
  _OrderBys: { 'Account':'asc', 'Phone':'desc' },  // 多字段排序
  _PageIndex: 1,
  _PageSize: 20
});

// 匿名查询（无需登录）
var result = V8.FormEngine.GetTableDataAnonymous('Article', { _PageSize: 10 });

// 匿名新增（无需登录，需谨慎开放）
var result = V8.FormEngine.AddFormDataAnonymous('Feedback', { Title: '意见', Content: '...' });

// 获取总数
var result = V8.FormEngine.GetTableDataCount('Sys_User', { _Where: [['Status', '=', 1]] });

// 获取树形数据
var result = V8.FormEngine.GetTableDataTree('Department', {});

// 新增数据
var result = V8.FormEngine.AddFormData('Sys_User', { Account: 'test', Name: '测试' });

// 批量新增
var addList = [{ FormEngineKey:'表名', Age:18 }, { FormEngineKey:'表名', Age:20 }];
V8.FormEngine.AddTableData(addList);

// 批量更新 / 批量删除
V8.FormEngine.UptTableData('Sys_User', [{ Id:'id1', Status:1 }, { Id:'id2', Status:0 }]);
V8.FormEngine.DelTableData('Sys_User', [{ Id:'id1' }, { Id:'id2' }]);

// 更新数据（需传Id）
var result = V8.FormEngine.UptFormData('Sys_User', {
  Id: 'xxx', Name: '新名字',
  _NotSaveField: ['字段1'],    // 忽略字段不更新
  _NoLineForAdd: true,         // 不存在则新增
  _ForceUpt: true              // 强制修改自动编号字段
});

// 按条件更新
var result = V8.FormEngine.UptFormDataByWhere('Sys_User', {
  _Where: [['Account', '=', 'test']],
  Status: 0
});

// 删除（单条 / 批量）
var result = V8.FormEngine.DelFormData('Sys_User', { Id: 'xxx' });
var result = V8.FormEngine.DelFormData('Sys_User', { Ids: [1,2,3] });

// 按条件删除
var result = V8.FormEngine.DelFormDataByWhere('Sys_User', {
  _Where: [['Status', '=', 0]]
});

// 仅在确实希望再次触发表单V8事件时使用Client；省略/Server不会重新触发
var result = V8.FormEngine.UptFormData('TableName', { Id: 'x', Field: 'val', _InvokeType: 'Client' });

// 新增字段（动态建表）
V8.FormEngine.AddField({
  TableName:'Diy_Test', Name:'Age', Type:'int',
  Label:'年龄', Component:'NumberText', TableWidth:'100', Visible:1
});
```

---

## _Where 条件语法

参数化查询，无 SQL 注入风险。支持 MySQL、Oracle、SqlServer。

```js
// 基本用法：[字段, 操作符, 值]
_Where: [['Account', '=', 'test']]

// AND/OR 条件：[AndOr, 字段, 操作符, 值]
_Where: [['Account', '=', 'test'], ['OR', 'Name', 'Like', '张']]

// 分组（括号）
_Where: [
  ['Name', 'Like', '张'],
  ['AND', '(', 'Age', '>', 18],
  ['OR', 'Status', '=', 'active', ')']
]

// In 查询
_Where: [['Id', 'In', ['id1', 'id2', 'id3']]]

// NULL 判断
_Where: [['Field', '=', null]]    // IS NULL
_Where: [['Field', '<>', null]]   // IS NOT NULL

// 日期查询
_Where: [['CreateTime', '>', DateFormat(new Date(), 'yyyy-MM-dd HH:mm:ss')]]
```

**支持的操作符：** `=`, `==`, `Equal`, `<>`, `!=`, `NotEqual`, `>`, `>=`, `<`, `<=`, `Like`, `NotLike`, `StartLike`, `EndLike`, `NotStartLike`, `NotEndLike`, `In`, `NotIn`

---

## V8.Db / V8.DbRead — 数据库操作

`V8.Db` 为主库（读写），`V8.DbRead` 为从库（只读）。`FromSql` 只传 SQL 字符串；动态值必须用 `.AddInParameter('@p0', value)` 链式绑定。普通单表查询优先使用 `V8.FormEngine.GetTableData + _Where`。

```js
// 查询列表
var list = V8.Db.FromSql('SELECT * FROM Sys_User WHERE Status = @p0')
  .AddInParameter('@p0', 1)
  .ToArray();

// 查询单条
var user = V8.Db.FromSql('SELECT * FROM Sys_User WHERE Id = @p0')
  .AddInParameter('@p0', userId)
  .First();

// 执行非查询
var affected = V8.Db.FromSql('UPDATE Sys_User SET Status = @p0 WHERE Id = @p1')
  .AddInParameter('@p0', 0)
  .AddInParameter('@p1', userId)
  .ExecuteNonQuery();

// 执行标量
var count = V8.Db.FromSql('SELECT COUNT(*) FROM Sys_User').ToScalar();

// 事务：接口引擎中 return Code=1 自动提交，Code≠1 自动回滚，禁止手动 Commit/Rollback
// 表单V8事件中：可共享事务
var result = V8.FormEngine.GetFormData('table', { Id: V8.Form.Id }, V8.DbTrans);

// 跨数据库（扩展库）
var dataList = V8.Dbs.OracleDB1.FromSql('SELECT * FROM table').ToArray();
// microi_database 的后端提交后事件调用此方法；事务提交后刷新全部节点
V8.Method.RefreshExtensionDatabases();
// 临时直连（只在当前请求内有效；连接字符串必须来自可信服务端配置，禁止直接使用 V8.Param）
var tempDb = V8.Dbs.Open('SqlServer', 'Server=127.0.0.1,1433;Database=app;User Id=user;Password=***;TrustServerCertificate=True;');
var tempList = tempDb.FromSql('SELECT * FROM Users WHERE Status = @p0')
  .AddInParameter('@p0', 1)
  .ToArray();
// 扩展库独立事务
var exTrans = V8.Dbs.EmptyEx.BeginTransaction();
exTrans.FromSql("DELETE FROM table WHERE Id = @p0")
  .AddInParameter('@p0', id)
  .ExecuteNonQuery();
exTrans.Commit();
exTrans.Close();
```

---

## V8.Cache — Redis 缓存

```js
V8.Cache.Set('key', 'value', 3600);            // 秒数过期
V8.Cache.Set('key', 'value', '0.00:00:59');    // d.HH:mm:ss 格式
var val = V8.Cache.Get('key');
V8.Cache.Remove('key');
var exists = V8.Cache.Exists('key');
var exists2 = V8.Cache.KeyExist('key');        // 真实接口名
V8.Cache.HashSet('hashKey', 'field1', 'value');
var hashVal = V8.Cache.HashGet('hashKey', 'field1');
var hashAll = V8.Cache.HashGetAll('hashKey');
V8.Cache.HashDelete('hashKey', 'field1');
// Key命名规范：Microi:${V8.OsClient}:{分类}:{Key}
```

---

## V8.Http — HTTP 请求

```js
// GET：必须使用对象参数格式
var result = V8.Http.Get({
  Url: 'https://api.example.com/data',
  GetParam: { page: 1 },
  Timeout: 600,                  // 秒，默认 10 分钟
  Headers: { token: 'xxx' }
});

// POST
var result = V8.Http.Post({
  Url: 'https://api.example.com/data',
  PostParam: { key: 'value' },
  ParamType: 'json',              // 'json' | 'form' | 'xml' | 'binary'
  Timeout: 600,                   // 秒，默认 10 分钟
  Headers: { token: 'xxx' },
  FilesByteBase64: {}             // 上传文件
});

// PATCH：与 POST 对称，使用 PatchParam / PatchParamString
var result = V8.Http.Patch({
  Url: 'https://api.example.com/data/1',
  PatchParamString: JSON.stringify({ nested: { enabled: true } }),
  ParamType: 'json'
});

// 完整响应：GetResponse / PostResponse / PatchResponse
var resp = V8.Http.PatchResponse({
  Url: 'https://api.example.com/data/1',
  PatchParam: { enabled: true },
  ParamType: 'json'
});
// resp.Content, resp.Headers, resp.RawBytes, resp.StatusCode, resp.ErrorMessage
```

---

## V8.Tcp — TCP 原始字节

```js
// ESC/POS 网络小票机（常用端口 9100）
var printResult = V8.Tcp.Send({
  Host: '192.168.1.88',          // 必须来自可信配置
  Port: 9100,
  Bytes: [27, 64, 29, 86, 0],   // 也可使用 ByteBase64 / Hex / Text
  ConnectTimeout: 10,
  SendTimeout: 10
});
if (printResult.Code !== 1) return printResult;

// 需要设备响应时
var response = await V8.Tcp.SendAndReceiveAsync({
  Host: '192.168.1.20',
  Port: 4001,
  Hex: '01 03 00 00 00 02 C4 0B',
  ReceiveTimeout: 3,
  MaxReceiveBytes: 65536
});
// response.Data.RawBytes / ByteBase64 / Hex / ReceiveEndReason
```

Bytes、ByteBase64、Hex、Text 必须且只能提供一种；目标主机和端口不得直接使用未受信任的请求参数。Code=1 只表示字节已写入 TCP 连接，不等于设备已经执行或小票已经出纸；不确定失败时自动重试可能重复打印。

---

## V8.ApiEngine — 调用其他接口引擎

```js
var result = V8.ApiEngine.Run('otherApiEngineKey', { param1: 'value1' });
// 共享事务（在表单V8事件中）
var result = V8.ApiEngine.Run('key', { Form: V8.Form }, V8.DbTrans);
```

---

## V8.MongoDb — MongoDB 操作

参数格式为对象，包含 DbName、TableName 字段。

```js
V8.MongoDb.AddFormData({ DbName:'mydb', TableName:'users', _FormData:{ name:'张三', age:25 } });
var doc = V8.MongoDb.GetFormData({ DbName:'mydb', TableName:'users', Id:'xxx' });
var docs = V8.MongoDb.GetTableData({ DbName:'mydb', TableName:'users', _Where:[['age','>',18]], _OrderBy:'CreateTime', _OrderByType:'DESC' });
V8.MongoDb.UptFormData({ DbName:'mydb', TableName:'users', Id:'xxx', _FormData:{ age:26 } });
V8.MongoDb.UptFormDataByWhere({ DbName:'mydb', TableName:'users', _Where:[['status','=',0]], _FormData:{ archived:true } });
V8.MongoDb.DelFormData({ DbName:'mydb', TableName:'users', Id:'xxx' });
V8.MongoDb.DelFormDataByWhere({ DbName:'mydb', TableName:'users', _Where:[['ownerId','=',V8.CurrentUser.Id],['status','=',0]] });
```

批量更新/删除必须使用非空参数化 `_Where`；禁止更新 `_id`。MongoDB 操作绑定当前 V8 租户且不参与 `V8.DbTrans`，业务重试应使用稳定幂等 Id。

---

## V8.Method — 内置方法

```js
var token = V8.Method.GetCurrentToken(token, osClient);   // 返回 {OsClient,CurrentUser,Token}
V8.Method.RefreshLoginUser(userId, osClient);
V8.Method.ClearUserLoginInfo(userId, osClient); // 管理员清除全部终端登录信息并吊销所有Token
V8.Method.RefreshExtensionDatabases(); // 事务提交后刷新全部节点的 V8.Dbs 缓存
var url = V8.Method.GetPrivateFileUrl({ FilePathName:'...' });
V8.Method.AddSysLog({ Type:'', Title:'', Content:'', Level:1 });
var guid = V8.Method.NewGuid();
var ulid = V8.Method.NewUlid();
var ts = V8.Method.GetTimestamp();             // Unix秒级时间戳
var oldWhere = V8.Method.ParseWhere(V8.Param._Where);     // 新版→旧版Where转换
// 文件上传
var upResult = V8.Method.Upload({
  FilesByteBase64: V8.FilesByteBase64,
  Limit: false, Preview: false, Path: '/test-upload', OsClient: V8.OsClient
});
```

---

## V8.EncryptHelper — 加密

```js
V8.EncryptHelper.MD5Encrypt('text');
V8.EncryptHelper.SHA256('text');
V8.EncryptHelper.SHA1('text');
V8.EncryptHelper.SHA512('text');
V8.EncryptHelper.Sha256Hex('text');
V8.EncryptHelper.HmacSha256(key, data);
V8.EncryptHelper.AESEncrypt('text', 'key');
V8.EncryptHelper.AESDecrypt(encrypted, 'key');
V8.EncryptHelper.DESEncode('text');            // DES加密
V8.EncryptHelper.DESDecode('cipher');          // DES解密
```

---

## V8.Base64

```js
V8.Base64.StringToBase64('Hello');       // 编码
V8.Base64.Base64ToString('SGVsbG8=');    // 解码
```

---

## V8.OCR — 图片/PDF 文字识别

OCR 服务地址、密钥、超时和配额统一由当前租户 SaaS 引擎的“OCR识别”Tab 配置，V8 参数不能覆盖这些服务端设置。

```js
var result = await V8.OCR.Recognize({
  FileByteBase64: V8.FilesByteBase64.invoice,
  FileName: 'invoice.png',
  UseDocOrientationClassify: true,
  UseDocUnwarping: true,
  UseTextlineOrientation: true,
  TextRecScoreThresh: 0.5,
  ReturnWordBox: false
});

if (result.Code !== 1) return result;
return { Code: 1, Data: result.Data };
```

支持 PDF、PNG、JPEG、BMP、GIF、TIFF、WebP。返回统一的全文、页列表、文本区域、多边形和置信度；大文件或批量识别应通过数据库/MQ/outbox 建立可恢复任务，不应依赖单节点内存队列。

---

## V8.Office

```js
V8.Office.SendEmail({
  SmtpServer:'smtp.qq.com', SmtpPort:587, EnableSSL:true,
  SystemEmail:'admin@itdos.com', SystemEmailPwd:'...',
  EmailSubject:'标题', EmailBody:'<b>HTML内容</b>',
  Receivers:['a@qq.com']
});
// 多 Sheet Excel：标准表格与高级 ExcelLayout 可以混用
var excelResult = V8.Office.ExportExcel({
  OsClient: V8.OsClient,
  ExcelOptions: { DefaultColumnWidth:14, HeaderRowHeight:28, FreezeHeader:true, AutoFilter:true },
  ExcelSheets: [
    { SheetName:'审批单', ExcelLayout:{
      Cells:[
        {Range:'A1:H1',Value:'盘盈亏及报废申请表',Merge:true,Style:{Bold:true,FontSize:18,HorizontalAlignment:'Center',BorderStyle:'Thin'}},
        {Range:'A2:H8',Style:{BorderStyle:'Thin',BorderColor:'7F8C9A'}},
        {Range:'A8:G8',Value:'合计',Merge:true},{Range:'H8',Formula:'SUM(H3:H7)',Style:{NumberFormat:'#,##0.00'}}
      ],
      Columns:[{Column:'A',Width:10},{Column:'H',Width:16}], Rows:[{Row:1,Height:42}]
    },ExcelOptions:{FreezeRows:2,PrintOrientation:'Landscape',PrintArea:'A1:H8'}},
    { SheetName:'客户', ExcelData:customerList, ExcelHeader:[{Name:'Name',Label:'客户名称',Component:'Text',Width:24}], ExcelOptions:{DataRowHeight:22} }
  ]
});
var rows = V8.Office.ExcelToList({ FileByteBase64: base64, SheetIndex: 0 });

// 富文本 Word；ExportWordText 继续兼容旧版纯文本
var wordResult = V8.Office.ExportWord({
  Title:'月度报告', HeaderText:'吾码', FooterText:'内部资料', ShowPageNumber:true,
  Paragraphs:[{Text:'正文',FirstLineIndent:0.74}],
  Tables:[{Headers:['指标','值'],Rows:[['销售额',1280000]]}]
});

// PowerPoint 多页导出
var pptResult = V8.Office.ExportPowerPoint({
  Title:'季度汇报', ShowSlideNumber:true,
  Slides:[
    {Layout:'TitleSlide',Title:'季度汇报',Subtitle:DateNow('yyyy-MM-dd')},
    {Title:'核心结论',Bullets:['收入增长','续约稳定']}
  ]
});
```

---

## V8.MQ — 消息队列 (RabbitMQ)

```js
V8.MQ.SendMsg('queue_name', { ProductId:'123', Count:2 });
// 消费者接口引擎中：
var message = V8.Param.Message;   // object类型
```

---

## V8.TranslateEngine — 翻译引擎

```js
V8.TranslateEngine.Translate('张三', 'en');           // 翻译为英文
V8.TranslateEngine.Translate('love', 'cn', 'en');     // 英→中
V8.TranslateEngine.TranslateText({                    // 批量/HTML/候选译文
  SourceTexts: ['你好', '世界'], FromLang: 'auto', Lang: 'en',
  Format: 'text', Alternatives: 2
});
V8.TranslateEngine.Detect({ SourceText: 'Bonjour' });
V8.TranslateEngine.GetLanguages();
V8.TranslateEngine.GetLang('NoAuth');                  // 从diy_lang缓存获取
```

---

## MQTT 引擎

```js
var eventName = V8.EventName;
// StartServer / Connected / Disconnected / MessageReceived / StopServer
if (eventName == 'MessageReceived') {
  var clientId = V8.MQTT.ClientId;
  var topic = V8.MQTT.Topic;
  var payload = V8.MQTT.Payload;
}
```

---

## 表单V8事件体系

### V8事件类型及执行顺序

| 事件文件 | 运行端 | 触发时机 | 说明 |
|----------|--------|---------|------|
| `InFormV8.js` | 前端 | 表单打开时 | 初始化字段显隐、默认值 |
| `SubmitFormV8.js` | 前端 | 表单提交前 | 前端校验（Postman不触发） |
| `SubmitBeforeServerV8.js` | 后端 | 数据写入DB前（事务中） | 后端校验、数据加工 |
| `SubmitAfterServerV8.js` | 后端 | 数据写入DB后（仍在事务中） | 触发通知、同步其它表 |
| `OutFormV8.js` | 前端 | 表单提交后/关闭后 | 刷新列表、跳转 |
| `DataFilterV8.js` | 后端 | 获取数据后每行执行 | 数据脱敏、字段加工 |

VS Code 本地资源文件名使用实时 `diy_field.Label`：`前端表单提交前V8事件（SubmitFormV8）.js`、`前端表单提交后V8事件（OutFormV8）.js`。不要继续生成旧名“前端表单提交V8事件/前端表单退出V8事件”。

### 后端V8事件特有变量
- `V8.Form` — 即将写入的数据
- `V8.OldForm` — 修改前的旧数据
- `V8.FormSubmitAction` — 'Insert' / 'Update' / 'Delete'
- `V8.DbTrans` — 共享事务（提交前/后事件都可用）
- `V8.NotSaveField` — 指定不保存的字段（数据脱敏）
- `V8.CacheData` — DataFilter中的缓存数据
- `V8.RowIndex` — 当前行索引

### 后端事件中阻止提交（自动回滚事务）
```js
return { Code: 0, Msg: '错误信息！' };
```

### 后端事件中共享事务操作其它表
```js
V8.FormEngine.UptFormData('other_table', { Id:'x', Field:'val' }, V8.DbTrans);
V8.ApiEngine.Run('key', { Form: V8.Form }, V8.DbTrans);
V8.FormEngine.GetFormData('this_table', { Id: V8.Form.Id }, V8.DbTrans);
```

### 工作流V8事件
```js
// 条件判断V8（决定流程走向）
if (V8.Form.Money <= 100) { V8.NextNodeId = 'node_id_1'; } else { V8.LineValue = 2; }
// 节点V8中可用
V8.WF.ApprovalType    // Agree/Disagree/Recall/Auto
V8.WF.ApprovalIdea    // 审批意见
V8.WF.CurrentNode     // 当前节点
V8.WF.NextNode        // 下一节点
V8.WF.NextTodoUsers   // 接收人
```

---

## 上下文变量

| 变量 | 说明 |
|------|------|
| `V8.Param` | 前端传入的请求参数（统一接收form/json/url三种） |
| `V8.Header` | 请求头 |
| `V8.CurrentUser` | 当前用户（Id, Account, Name, RoleIds, RoleName, DeptId, DeptIds, DeptName, Level） |
| `V8.OsClient` | 当前应用标识 |
| `V8.SysConfig` | 当前租户非敏感系统配置的脱敏副本 |
| `V8.Limits` | 当前执行片段的超时、语句、单层/调用树累计分配、递归和接口嵌套预算 |
| `V8.OsClientModel` | 当前租户SaaS配置的脱敏副本；数据库、认证、Redis、存储、MQ等机密不会注入 |
| `V8.Form` | 当前表单数据（V8事件中） |
| `V8.OldForm` | 提交前的旧数据（V8事件中） |
| `V8.TableModel` | 当前diy_table信息（V8事件中） |
| `V8.FormSubmitAction` | 提交动作：Insert / Update / Delete |
| `V8.EventName` | 事件名称 |
| `V8.InvokeType` | 调用类型：Server / Client |
| `V8.Result` | 赋值后作为接口返回值 |
| `V8.Action` | GetDateTimeNow(), GetTimestamp(), Sleep(ms) |
| `V8.FilesByteBase64` | 接收上传的文件数据 |

---

## DosResult 标准返回格式

```js
{ Code: 1, Data: {}, DataCount: 0, Msg: '', DataAppend: {} }
// Code: 1=成功, 0=失败, 2=GetFormData数据不存在, 1001=Token失效, 1002=身份验证失败
```

---

## SaaS引擎 — 三参数模型

接口引擎区分租户：
```js
// 方式1：传token自动识别
// 方式2：URL参数 /apiengine/test?OsClient=veken
// 方式3：特殊格式 /apiengine/test--OsClient--veken--
```

---

## .NET 互操作

新代码优先使用 `V8.*`、`DateNow`、`V8.Method.NewUlid` 和 `V8.Base64`。不要依赖任意 CLR 类型；平台同时提供 `V8.System` 主机监控扩展，全局 `System` 可能发生名称冲突，且危险 CLR 类型会被禁用。

---

## 全局函数

```js
DateNow('yyyy-MM-dd HH:mm:ss')                        // 当前日期时间
DateFormat(dateObj, 'yyyy-MM-dd')                       // 日期格式化
DateAdd(date, 'd', 1, 'yyyy-MM-dd')                    // 日期加减（支持s/m/h/d/w/q/M/y）
console.log('调试信息')                                  // 控制台输出（docker logs查看）
```

---

## 接口引擎注意事项

- 数组参数：`Array.isArray(V8.Param.arr)` 返回 false，但 `arr.length` 和 `arr[0]` 正常
- 事务管理：平台事务禁止手动 Commit/Rollback；带Code对象仅Code=1提交、无Code对象回滚，原始值无异常时提交
- `_InvokeType: 'Client'`：FormEngine调用时触发表单V8事件（默认Server模式不触发）
- 后端可信V8调用FormEngine不要求 `_SysMenuId`；浏览器不能通过 `_InvokeType` 伪造信任


## Microi吾码非阻塞自动更新规范（强制）

- VS Code 扩展、`@microi.net/cli`、Codex 插件与检测到的 DeepSeek Harness profile bundle 默认在后台从官方分发源检查和安装更新；更新检查不得成为分析、MCP 调用、源码修改、构建、发布或任何新任务的前置门禁。
- CLI 使用 npm 官方 registry：`npm view '@microi.net/cli' version --json --prefer-online --registry=https://registry.npmjs.org/`；VS Code 扩展使用官方扩展宿主的安装/自动更新能力。禁止用第三方 registry 或不明镜像冒充官方更新。
- 自动更新由 `microi update --background --workspace "<工作区绝对路径>" --json` 投递。它会在后台升级全局 CLI、更新 Codex 插件与 DeepSeek Harness bundle；仅当工作区已有有效 Microi 服务器连接时，才幂等执行 `microi ai init` 与 `microi doctor`，随后执行 `microi codex status` 与 `microi dsh status`；未检测到 DSH 时安静跳过。`codex install --yes` 中的 `--yes` 只为兼容旧脚本，不再代表工作授权门槛。
- 当前运行中的扩展、CLI、Codex Router、DSH 会话和 MCP 继续使用已加载版本；不得为了升级杀进程、强制重载窗口、终止对话或暂停用户任务。新版本只在后续新进程或宿主自然重启时接管。
- registry 不可用、权限不足、文件被运行中任务占用、安装失败或宿主暂不支持热更新时，记录可诊断状态并在后台延后重试；可以非模态提示用户“立即重试/查看日志”，但无论用户是否处理，都必须允许当前、正在进行和新建工作继续。


## 接口引擎与应用商城优先规范（强制）

- 新增业务逻辑先判断现有低代码 CRUD/表单事件能否完成；其次使用接口引擎。只有缺少可复用底层原子能力时才扩展 V8，并继续由接口引擎编排；平台协议、可信鉴权、密钥隔离、存储/网络边界和运行时内核才允许直接写 C# Controller/Service。
- 修改 `Microi.Server` 前必须说明为什么不能使用接口引擎。第三方 HTTP 集成默认使用 `V8.Http`；密钥不能暴露给可编辑 V8 时，只在 C# 提供最小、租户隔离且不可覆盖密钥的安全原子方法。第三方回调采用“C# 最小协议网关 + `Managed` 核心接口引擎 + `CreateIfMissing` 租户 Hook”，C# 不承载日志、写表、通知等业务。
- 第三方不支持 QueryString 时使用 `/path--OsClient--{OsClient}--`；支持 Query 时固定使用 `?OsClient=`，禁止 `?o=`。路径与 Query 同时出现时必须一致。
- 表、字段、Tab、菜单、权限、接口引擎、事件、数据源、页面、打印、工作流、任务和可幂等种子数据必须优先通过应用商城升级，不得为这些资源在 `Microi.Server/Microi.Upgrade/` 新增定制 .NET 迁移。
- 应用包接口引擎必须声明 `ResourcePolicies.ApiEngines`。官方核心使用 `Managed`，仅当目标端 `Local == Base` 才更新；租户扩展使用 `CreateIfMissing`，首次创建后永不覆盖，同一 Key 后续也禁止改回 `Managed`，确需官方接管时发布新 Key。发现核心被客户修改时整包冲突回滚，不自动合并可执行代码。
- 有官方权限时使用绑定 `https://api.itdos.com`、`OsClient=iTdos` 的 `microi_itdos` 更新并发布官方应用，再由目标租户 MCP 安装/更新和回读；无官方权限时只通过当前用户自己的 MCP/Manifest 升级其数据库。
- `Microi.Upgrade` 只保留应用商城运行前必需的核心物理兼容/协议迁移，并要求版本门、共享租约、幂等和失败不推进版本。禁止每次启动按租户重跑不断增长的历史迁移清单。详细规则读取 `microi.skills/workspace-conventions/SKILL.md` 与 `microi.skills/app-store/SKILL.md`。


## Microi 工作区强制规则唯一来源

进度播报、分布式与重启安全、本地 OOM 保护、版本日志保护等工作区级规则只维护在 `microi.skills/workspace-conventions/SKILL.md`。处理 Microi 任务前必须读取该入口，并按其渐进披露路由读取与当前任务相关的参考文件；不得在 AGENTS.md 或生成模板中复制规则正文。


## 后端 API 配置白名单与 SaaS 单一事实源（强制）

- `Microi.net.Api` 的 `AppSettings` 与同名容器环境变量只允许：`OsClient`、`OsClientType`、`OsClientNetwork`、`OsClientDbType`、`OsClientDbConn`、`OsClientRedisHost`、`OsClientRedisPort`、`OsClientRedisPwd`、`OsClientRedisDataBase`、`OsClientDbMongoConn`。
- 除上述十项外，业务开关、重试、超时、限额、安全策略、密钥和可执行文件路径必须进入 SaaS 引擎 `sys_osclients` 的合适 Tab；禁止新增 `MICROI_*`、`DOS_ORM_*`、额外 `AppSettings` 节点或动态环境变量读取。
- `ASPNETCORE_*`、`DOTNET_*` 只属于 .NET 宿主；测试、构建、安装、MCP 和发布脚本可使用自身进程变量，但生产 API 不得读取它们控制业务行为。
- 新配置必须配套幂等升级、默认值、缓存刷新、敏感字段脱敏、子租户隔离、文档和源码扫描测试；验收需扫描生产源码、API 配置及在线/离线 Compose。


---

## 数据库结构

数据库结构不会写入本基础知识库文件，避免不同开发者连接不同服务器后产生提交冲突。

编写 `V8.FormEngine` 或 `V8.Db` 代码时：
- 优先通过 MCP 工具 `microi_get_db_schema` 获取当前服务器的实时表结构。
- 如需读取本地快照，请查看当前引擎文件所属 OsClient 目录下的 `.microi-db-schema.md`。

从自然语言需求创建完整 Microi 低代码系统时：
- 先调用 `microi_get_db_schema` 了解已有表、菜单、字段，避免重复建模。
- 再调用 `microi_get_manifest_schema` 获取完整 Manifest 协议和示例。
- 将需求整理为 Manifest，模块配置优先写字段名：`listFields`、`searchFields`、`sortFields`、`hiddenFields`、`mobileFields`、`cardTitleFields`、`cardBottomFields`。MCP 会自动解析为 `diy_field.Id`、`SelectFields`、`SearchFieldIds` 等 `sys_menu` 所需格式。
- 创建绑定 `diyTableId` 的后台菜单时，必须配置或允许 MCP/后端自动推断 `TableDiyFieldIds`、`SelectFields`、`SearchFieldIds`、`SortFieldIds`、`NotShowFields`、`StatisticsFields`、`MobileListFields`、`CardTitleTagFields`、`CardBottomTagFields`、`DefaultOrderBy`。
- `NotShowFields` 默认隐藏 Id/外键/系统字段/布局控件/上传富文本地图子表等重字段；`SearchFieldIds` 默认选择名称、标题、编号、状态、分类、负责人、时间等常用筛选；`StatisticsFields` 默认选择金额、价格、数量、积分、余额等数值字段；移动端/卡片列默认保留 3-4 个核心可读字段。
- 表单控件以 `Microi.Client/src/views/form-engine/diy-field-component/diy-component-list.json` 为事实源。字段较多时优先使用 `diy_table.Tabs` 和字段 `Tab` 分组，局部复杂区域再用 `CollapseGroup` 或字段级 `Tabs` 控件折叠/分段。
- 生成或新增字段时，普通字段默认不要设置 `diy_field.FormWidth`（保持 null/省略）；只有 `CodeEditor`、`Textarea`、`RichText`、上传、子表、地图/布局/自定义等需要独占整行的控件才设置为 `24`。
- 生成审批流时，Manifest 的 workflows 需包含 FlowDesign、Nodes、Lines；连线标题默认使用 `{起点节点} 到 {终点节点}`，多路线节点优先生成设置 `V8.NextNodeId` 的 `LineValueV8`。
- 保存工作流前调用 `microi_check_workflow_package` 检查拓扑，必要时用 `microi_test_workflow_condition` 带样例表单数据测试图形条件路线。
- 调用 `microi_plan_system` 做本地结构检查，再调用 `microi_generate_system` 且保持 `dryRun:true`。
- 只有用户明确同意写入时，才用 `dryRun:false` 并传 `confirmExecution`，随后调用 `microi_validate_system` 验收。


## JoinForm 与 TableChild 关系门禁（强制）

- 先确定关系基数：`JoinForm` 只允许 1:1/N:1，目标表必须与当前表不同，`joinFieldName` 必须是当前主表中已存在且真实保存目标记录 Id 的字段；禁止默认写成 `Name`。
- “子表、明细、清单、条目、行项目、多个记录”默认是 1:N，必须使用 `TableChild`。在独立子表创建真实父级外键和以 `(OsClient, FK)` 开头的组合索引，并创建绑定子表且 `display=0、appDisplay=0、hasChild=0` 的隐藏模块。
- 完整系统 Manifest 的关系字段必须写可移植 `relation`：JoinForm 使用 `{cardinality:"N:1",targetTable,joinFieldName}`；TableChild 使用 `{cardinality:"1:N",targetTable,childForeignKey,childModule,primaryTableFieldName:"Id"}`。禁止在 Manifest 中编造 `diy_table.Id` 或 `sys_menu.Id`。
- `microi_plan_system` / `microi_generate_system` 会在任何写入前拒绝自关联、基数/组件不符、缺外键、缺隐藏子菜单或缺回查索引；生成器会在表、普通字段和菜单就绪后才解析当前租户真实 Id 并写关系字段。不得改用单字段工具绕过；后端 MCP 边界会再次校验。


## 数据库索引 MCP 规范（强制）

- 需求、蓝图、接口、Job 或评审一旦明确某表字段需要索引，必须写入 Manifest `tables[].indexes`，并调用 `microi_create_table_index`；禁止在 V8、接口引擎、FormEngine 或一次性 SQL 中手写 CREATE/DROP INDEX。
- 创建前后调用 `microi_get_table_indexes` 回读真实物理索引。删除只能用 `microi_drop_table_index`，主键索引禁止删除。
- 租户业务组合索引通常以 `OsClient` 开头；业务唯一键、幂等键用租户范围唯一索引；外键、子表、Job/outbox/待办扫描按真实 WHERE/JOIN/ORDER BY 设计。
- 不得把 SearchFieldIds、SortFieldIds、StatisticsFields 机械转换成一批单列索引；低基数字段、LIKE '%keyword%' 和长文本不能滥用普通 B-tree 索引。
- DIY 表索引回读后还必须能在 Microi.Client “开发设计 → 索引管理”看到相同名称、有序字段与唯一性。


## MCP 默认显隐规则

- 创建 `sys_menu` 菜单模块时，除非用户明确要求隐藏，否则 `Display` 和 `AppDisplay` 默认设为 `1`。
- 绑定 `diyTableId` 的菜单默认补齐列表列、搜索列、隐藏列、排序列、统计列、移动端/卡片列和默认排序；用户显式传入的 `sys_menu` JSON 优先。
- 创建 `diy_field` 字段时，除非用户明确要求隐藏，否则 `Visible` 和 `AppVisible` 默认设为 `1`。
- 字段较多的表单默认优先生成 `diy_table.Tabs`，并给字段写入 `Tab`；整行控件才使用 `FormWidth=24`。


## AI 菜单模块视觉交付门禁（强制）

- 每个可见、绑定表的模块都必须配置紧凑 Hero 标题、业务副标题和 2-4 个真实动态指标。指标优先选择金额、数量、余额、进度、逾期、待处理等业务聚合；没有合适数值字段时使用真实 `DataCount`、`PageCount` 或真实状态分布兜底。禁止随机数、固定演示数、伪统计或只写毫无业务意义的总数。
- 每个列表字段都要按字段语义设置合理 `TableWidth`。PC 复合列必须给足 `MinWidth`，组织主字段、多行副字段、右侧图标/状态，并从普通列中排除已经展示的重复字段，同时保留查询依赖字段。
- 移动端卡片应按真实业务字段设计图片、标题、副标题、顶部标签、右侧金额/状态、内容、Meta 与底部字段；同一字段不得跨区域重复堆叠。
- 菜单动态统计角标只用于少数高价值待办/异常/未读入口；页面多 Tab 和更多 V8 按钮有真实业务计数时也应配置角标。批量角标必须避免 N+1 查询并提供安全降级。
- 模块设计器固定提供“模块标题与统计、PC 复合列、移动端卡片、自定义表单、高级 JSON”五个入口。`EnableViewSchema` 只控制 Detail/Edit 自定义表单；关闭后紧凑标题、动态指标、列表密度、PC 复合列和移动端卡片仍然生效。
- 平台自动生成的 List/Card 与真实数据兜底只是最低保障。AI 交付时仍须根据业务语义主动完善并回读验证，不得因为平台已有默认值而省略设计。


## MCP 写入超时、源码完整性与回读规则

- 优先使用语义明确的标准 MCP 工具：接口引擎代码用 `microi_save_engine_code`，表单事件用 `microi_save_event_code`，菜单按钮、Tab、SqlJoin、SqlWhere 用 `microi_update_module`。不要先绕到原生 HTTP、FormEngine 或 SQL。
- MCP 写请求超时只表示客户端未及时收到响应，不表示服务器一定没有写入。上述标准写工具以及 `microi_create_engine` 会自动短超时回读；返回 `RecoveredAfterTransportError:true` 时应视为已确认成功。
- 恢复性回读必须使用独立短超时，不能沿用普通查询长超时并长期停留在“等待远端回读”。如果标准工具返回“写入结果不确定”，只用对应 get 工具继续回读一次并报告真实差异。
- `…N tokens truncated…`、`Exit code:`、`Chunk ID:`、`Wall time:` 是 AI/终端工具包装文本，不是 V8 源码。读取长源码必须按 MCP 返回的字符区间取完并核对 SHA-256；插件推送和 MCP 写工具检测到这些标记时必须拒绝写入。远端源码不少于 8000 字符且新源码突然减少超过 15% 时，未核对完整源码前不得确认大幅删减。
- 禁止因为超时重复建表、重复加字段、重复创建接口引擎，或新建一次性维护引擎绕过原操作。创建接口引擎数据库入库成功但路由缓存刷新超时时，应保留成功结果并检查 `CacheRefresh`，不能当作创建失败重复提交。
- `MoreBtns`、`FormBtns`、`PageTabs`、`BatchSelectMoreBtns` 等菜单字段始终向 MCP 传明文 JSON 数组。租户表单事件中的 Base64 兼容逻辑属于平台内部细节，AI 不得自行编码。
- VS Code 设置里显示 MCP 已启用只代表配置存在。插件“诊断 MCP 可调用性”必须完成 `initialize`、`tools/list` 和真实 `microi_get_status`。
- 遇到 `ByteString` 或 `greater than 255` 时，先按异常字符索引检查 HTTP Header。Microi MCP 的设备标识来自 `did` / `MICROI_MCP_DID`；中文 Windows 主机名会从 `MCP:` 后第 4 个字符触发错误。`MICROI_LABEL_BASE64` 只用于显示，不是请求 Header，不得先猜测或改写中文 Label。连接恢复前禁止远端写入，恢复后先做只读基线盘点。
- Codex 未注入普通 MCP 工具时，先调用 `list_mcp_resources` 并读取 `microi://codex/status`；通用调用使用 `list_mcp_resource_templates` 发现 `microi://codex/action/{action}/{params}`，其中 params 是 URI 编码 JSON。该资源模板仍复用原工具的 schema、确认口令、审计和回读规则，不得改走原生 HTTP/SQL。


## V8 源码同步保护规则（强制）

- 多人开发时，每次准备推送接口引擎、表单/字段 V8、模块按钮、模块 SqlJoin/SqlWhere 或流程节点 V8 前，必须先按当前服务器和引擎分类检查同步状态。不得凭本地文件时间或上次对话结论直接覆盖远端。
- 只有 `localModified` 可以推送；`remoteModified` 必须先拉取；`remoteDeleted` 表示服务器已删除且本地未改，拉取时先备份再清理；服务器已删除但本地也修改时按 `conflict` 处理；`conflict` 必须比较同步基线、本地和远端后合并。无同步基线或预检失败时停止推送。
- 插件“推送当前文件”必须自动执行上述预检；一键同步可以复用刚完成且无冲突的完整快照，并覆盖接口引擎、表单事件、字段 V8、模块按钮、模块 SqlJoin/SqlWhere 和流程节点。正文一致仅 meta/mtime 不一致时自动校准。
- AI 通过 MCP 直接写远端后，要回读生效代码并同步本地文件、`.microi-meta.json` 和 mtime。工作结束前再次检查，并报告本地未推送、远端较新、服务器已删除、冲突是否为 0。


## MCP 在线应用默认发现与复杂页面规则

- 处理 Web、UniApp、MicroService、定制弹窗或复杂页面前，先调用 `microi_list_applications` 获取当前租户所有在线应用及完整文件清单，再对目标应用调用 `microi_get_application_context` 读取元数据、哈希、运行时和必要的小文件；单文件按需使用 `microi_get_application_file`。返回清单后还必须检查 `ContentsComplete/ContentErrorCount` 和逐文件 `ContentReadError`，不能把“有清单”误报成“源码完整可读”。
- 已有合适 MicroService 时优先新增页面/路由；没有时先用 `microi_scaffold_vue_microservice` 在当前租户 `AI应用/{appKey}` 目录预演并确认生成 Vue 脚手架，再依次调用 `microi_create_microservice`、`microi_sync_microservice_source`、`microi_publish_application_directory_stream`。
- 流式发布失败时必须读取 `uploadedCount/retrySafe`；只有尚未上传任何文件、明确可安全重试且编译产物较小时，才可临时回退 `microi_publish_microservice`，并在结论中记录远端版本缺口。
- 每个微服务页面菜单必须通过 `microi_create_module` 绑定 `MicroServiceId/MicroServicePageId/MicroServiceRoutePath/MicroServiceKey`，随后用 `microi_get_module` 回读；普通 URL 菜单成功不等于微服务菜单已交付。
- 拉取已有 MicroService 源码前必须比较上次同步基线、本地文件和私有 HDFS 源码，先展示仅本地、仅远端和冲突文件；用户明确确认后才能强制覆盖。
- 构建并推送 MicroService 时必须先成功同步完整源码到当前租户私有 HDFS，再发布公有编译产物；源码失败时禁止继续发布。
- `V8.ConfirmTips` 只用于纯文本确认或极少量一次性输入。三个以上字段、联动校验、上传、表格、Tab、步骤条、代码编辑器或需长期维护的弹窗，必须使用微服务页面并通过 `V8.OpenAppDialog` 打开，禁止在 V8 代码里拼接大段 HTML。
- 应用商城历史字段 `AppType` 表示官方/社区分类；运行应用类型使用 `ApplicationType`，值为 `Regular / MicroService / UniApp / Web`。


## MicroService 大型产物与上下文规则（覆盖旧兼容说明）

- `microi_get_application_context` 默认只读元数据、哈希、运行时和页面；少量正文显式开启内容读取，单文件使用 `microi_get_application_file`。
- 本地源码同步调用 `microi_sync_microservice_source` 时只传项目绝对路径 `directory`，由 MCP 进程扫描、哈希和读取文件；禁止把源码读成 Base64、生成 `.sync-seg-*` / `sync-source-files.json` 或把一个文件人工分段。模型上下文只接触清单。
- 新脚手架必须支持独立地址运行：无宿主 Token 时显示吾码帐号密码登录，并按 `V8.GetSysConfig(true).EnableCaptcha` 动态加载验证码；菜单和 `V8.OpenAppDialog` 入口复用宿主 Token。
- 菜单、弹层和组件宿主必须传递 `permissionContext={sysMenuId,moduleEngineKey,diyTableId}`。无权限按 Token/OsClient、ModuleEngineKey、宿主上下文、角色授权顺序排查，禁止改匿名或去掉权限校验。
- 真实编译目录一律逐文件流式发布，支持最多 20,000 文件/总计 20GB；几百 MB、1GB 级项目不得回退 Base64。
- `StorageMode=db` 的 256 文件/5MB 仅用于显式小型应急恢复，不是正常发布容量。
- 流式失败读取 `uploadedCount/retrySafe` 并按同版本幂等重试；禁止因大文件自动改走 `microi_publish_microservice`。
- 子租户所有源码、资产、回读验签、页面和缓存必须绑定当前 Token 的 OsClient，不得回退主租户默认配置。


## MicroService 发布后运行探测与 502 恢复规则

- 发布回读后还必须直接探测稳定入口、版本入口和清单内 JS/CSS；元数据、页面路由和菜单存在不能证明页面可运行。
- 若稳定入口返回 502，优先检查 API 节点通过租户 MinIO 内网端点读取公有桶的链路，禁止用重复发布掩盖存储读取故障。
- 服务器暂未部署修复且产物很小时，可短期使用数据库内联资源恢复；修复部署后必须重新流式发布并恢复 HDFS，禁止长期把大 JS/CSS 放在数据库 JSON。


## 官方文档原位增补与中文单源规则

- 修改官方文档前先搜索已有页面并原位补充；除非确有长期独立主题，不得新建相近 Markdown 页面、导航项或页面路由。
- 前端 V8 API 固定维护 `microi.doc/docs/doc/v8-engine/v8-client.md`，后端 V8 / 接口引擎 API 固定维护 `microi.doc/docs/doc/v8-engine/v8-server.md`。
- 日常功能开发只维护 `microi.doc/docs/doc/` 中文文档；`microi.doc/docs/en/` 由官网统一翻译生成，不手工重复编写英文版。
- 前端新 HTTP 代码优先使用与后端参数基本一致的 `V8.Http`；旧 `V8.Post/Get` 只作兼容保留。


---

## Microi 项目技能规范

处理 Microi 低代码系统、V8 引擎、PC 前端、UniApp/H5/小程序、Microi.UI、MCP 建模、自动化测试或交付复盘时，必须先按任务类型读取相关 skill 文件；不要只在编写 V8 代码时才参考 skills（共 65 个）。普通用户在空工作区安装插件后，只要通过插件执行初始化或拉取，AI 就应自动识别这些规则，不需要再手动要求“严格遵循 skills”：
- `microi.skills/v8-crud-api/SKILL.md` — Microi V8 CRUD API 接口引擎开发
- `microi.skills/v8-sql-query/SKILL.md` — Microi V8 安全 SQL 查询
- `microi.skills/v8-table-event/SKILL.md` — Microi V8 表单事件开发
- `microi.skills/v8-cache-pattern/SKILL.md` — Microi V8 Redis 缓存模式
- `microi.skills/v8-http-integration/SKILL.md` — Microi V8 HTTP 外部接口集成
- `microi.skills/v8-tcp-integration/SKILL.md` — Microi V8 TCP 原始字节集成
- `microi.skills/v8-mongodb/SKILL.md` — Microi V8 MongoDB 操作
- `microi.skills/v8-mq-mqtt/SKILL.md` — Microi V8 消息队列与 MQTT
- `microi.skills/v8-workflow/SKILL.md` — Microi V8 工作流事件开发
- `microi.skills/v8-api-config/SKILL.md` — Microi V8 接口引擎配置
- `microi.skills/v8-saas-multi-tenant/SKILL.md` — Microi V8 SaaS 多租户引擎
- `microi.skills/v8-image-processing/SKILL.md` — Microi V8 图像处理
- `microi.skills/v8-file-upload/SKILL.md` — Microi V8 文件上传下载
- `microi.skills/v8-export-import/SKILL.md` — Microi V8 Office 导入导出
- `microi.skills/v8-debugging/SKILL.md` — Microi V8 调试与日志
- `microi.skills/v8-security/SKILL.md` — Microi V8 安全最佳实践
- `microi.skills/v8-utilities/SKILL.md` — Microi V8 通用能力与函数索引
- `microi.skills/ocr-engine/SKILL.md` — Microi OCR 引擎
- `microi.skills/spider-engine/SKILL.md` — Microi 采集引擎
- `microi.skills/v8-frontend-events/SKILL.md` — Microi V8 前端事件大全
- `microi.skills/v8-template-engine/SKILL.md` — Microi V8 模板引擎（表格/表单 V8 模板）
- `microi.skills/v8-menu-buttons/SKILL.md` — v8-menu-buttons — 菜单按钮 / Tab / 批量操作 V8 写法
- `microi.skills/microi-client-frontend/SKILL.md` — Microi.Client 前台源码架构说明
- `microi.skills/page-engine/SKILL.md` — Microi 界面引擎（Page Engine）页面 JSON 生成
- `microi.skills/print-engine/SKILL.md` — Microi 打印引擎（Print Engine）模板 JSON 生成
- `microi.skills/ui-design/SKILL.md` — Microi吾码设计规范
- `microi.skills/microi-ui/SKILL.md` — Microi.UI / MCI-UI
- `microi.skills/microi-form-engine/SKILL.md` — Microi 表单引擎设计
- `microi.skills/microi-form-layout/SKILL.md` — Microi 表单布局分组规范（Tabs vs CollapseGroup）
- `microi.skills/microi-db-schema/SKILL.md` — Microi DB Schema
- `microi.skills/module-engine/SKILL.md` — Microi 模块引擎
- `microi.skills/dos-orm/SKILL.md` — Dos.ORM
- `microi.skills/microi-left-right-layout/SKILL.md` — Microi 左右树表配置规范
- `microi.skills/datasource-engine/SKILL.md` — Microi 数据源引擎
- `microi.skills/job-engine/SKILL.md` — Microi Job 定时与后台任务
- `microi.skills/message-notification/SKILL.md` — Microi 消息通知
- `microi.skills/search-engine/SKILL.md` — Microi SearchEngine
- `microi.skills/report-engine/SKILL.md` — Microi 报表引擎
- `microi.skills/translate-engine/SKILL.md` — Microi TranslateEngine
- `microi.skills/ai-engine/SKILL.md` — Microi AI Engine
- `microi.skills/ai-platform-governance/SKILL.md` — Microi吾码 AI 平台治理中心
- `microi.skills/system-observability/SKILL.md` — Microi 系统日志/监控
- `microi.skills/app-store/SKILL.md` — Microi 应用商城
- `microi.skills/microi-sso/SKILL.md` — Microi SSO 身份联邦
- `microi.skills/business-blueprint/SKILL.md` — Microi 业务架构蓝图（System Blueprint）
- `microi.skills/microi-system-delivery/SKILL.md` — Microi 全系统交付复盘与总控规范
- `microi.skills/microi-deployment/SKILL.md` — Microi 安装与部署
- `microi.skills/microi-microservice/SKILL.md` — Microi 前端微服务
- `microi.skills/microi-ai-application/SKILL.md` — Microi AI 应用
- `microi.skills/unity-integration/SKILL.md` — Microi Unity 完整交付
- `microi.skills/microi-docs-coverage/SKILL.md` — Microi 中文官网文档与 Skills 覆盖审计
- `microi.skills/microi-solution-quotation/SKILL.md` — Microi吾码解决方案与报价
- `microi.skills/microi-frontend-sdk/SKILL.md` — Microi 前端 SDK
- `microi.skills/microi-uniapp-frontend/SKILL.md` — Microi UniApp 前端通用规范
- `microi.skills/microi-mobile-app-quality/SKILL.md` — Microi 移动端质量门禁
- `microi.skills/microi-datasource-mapping/SKILL.md` — microi-datasource-mapping — 数据源 Key/Value 映射规范
- `microi.skills/v8-formengine-http/SKILL.md` — FormEngine HTTP 路由约定（外部系统调用）
- `microi.skills/v8-explorer-tree/SKILL.md` — v8-explorer-tree — V8 资源管理器目录规范 v2（2026-05）
- `microi.skills/workspace-conventions/SKILL.md` — Microi 工作区全局约定
- `microi.skills/microi-codex-installer/SKILL.md` — Microi吾码 AI 插件与 CLI 安装
- `microi.skills/microi-codex/SKILL.md` — Microi吾码 Codex / DeepSeek Harness Plugin
- `microi.skills/production-readonly-audit/SKILL.md` — Microi 正式环境只读业务巡检
- `microi.skills/uniapp-mall-assets/SKILL.md` — Microi UniApp / 商城资源路径规范
- `microi.skills/playwright-e2e/SKILL.md` — Microi 吾码 Playwright E2E 自动化测试
- `microi.skills/performance-testing/SKILL.md` — Microi 高并发性能压力测试
